-- Script generated by Redgate Compare v1.18.0.11708


-- deployment: Dropping Products...
DROP TABLE Products;


-- deployment: Dropping Customers.Email...
DROP INDEX Email ON Customers;


-- deployment: Dropping Customers...
DROP TABLE Customers;


-- deployment: Dropping AnotherRandomTables...
DROP TABLE AnotherRandomTables;


-- deployment: Dropping AnotherRandomTable...
DROP TABLE AnotherRandomTable;


-- deployment: Creating Appointments...
CREATE TABLE Appointments (
    AppointmentID int(11) NOT NULL,
    PatientID int(11) NULL,
    DoctorID int(11) NULL,
    AppointmentDate datetime NULL,
    Diagnosis varchar(100) NULL,
    Prescription text NULL
);
ALTER TABLE Appointments ADD PRIMARY KEY (AppointmentID);


-- deployment: Creating Appointments.PatientID...
CREATE INDEX PatientID USING BTREE ON Appointments(PatientID);


-- deployment: Creating Appointments.DoctorID...
CREATE INDEX DoctorID USING BTREE ON Appointments(DoctorID);


-- deployment: Creating Doctors...
CREATE TABLE Doctors (
    DoctorID int(11) NOT NULL,
    FirstName varchar(50) NULL,
    LastName varchar(50) NULL,
    Specialization varchar(50) NULL,
    PhoneNumber varchar(20) NULL
);
ALTER TABLE Doctors ADD PRIMARY KEY (DoctorID);


-- deployment: Creating Appointments.Appointments_ibfk_2...
ALTER TABLE Appointments
    ADD CONSTRAINT Appointments_ibfk_2 FOREIGN KEY (DoctorID)
    REFERENCES Doctors(DoctorID)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


-- deployment: Creating Patients...
CREATE TABLE Patients (
    PatientID int(11) NOT NULL,
    FirstName varchar(50) NULL,
    LastName varchar(50) NULL,
    Gender enum('Male','Female','Other') NULL,
    DateOfBirth date NULL,
    Address varchar(100) NULL,
    PhoneNumber varchar(20) NULL
);
ALTER TABLE Patients ADD PRIMARY KEY (PatientID);


-- deployment: Creating Appointments.Appointments_ibfk_1...
ALTER TABLE Appointments
    ADD CONSTRAINT Appointments_ibfk_1 FOREIGN KEY (PatientID)
    REFERENCES Patients(PatientID)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;

