-- Script generated by Redgate Compare v1.18.0.11708


-- deployment: Dropping Appointments.Appointments_ibfk_2...
ALTER TABLE Appointments DROP FOREIGN KEY Appointments_ibfk_2;


-- deployment: Dropping Appointments.DoctorID...
DROP INDEX DoctorID ON Appointments;


-- deployment: Dropping Doctors...
DROP TABLE Doctors;


-- deployment: Dropping Appointments.Appointments_ibfk_1...
ALTER TABLE Appointments DROP FOREIGN KEY Appointments_ibfk_1;


-- deployment: Dropping Appointments.PatientID...
DROP INDEX PatientID ON Appointments;


-- deployment: Dropping Patients...
DROP TABLE Patients;


-- deployment: Dropping Appointments...
DROP TABLE Appointments;

