-- Script generated by Redgate Compare v1.18.0.11708


-- deployment: Creating AnotherRandomTables10...
CREATE TABLE AnotherRandomTables10 (
    ID int(11) NOT NULL,
    Description varchar(100) NULL,
    RandomFloatValue float NULL
);
ALTER TABLE AnotherRandomTables10 ADD PRIMARY KEY (ID);

