name: Lint Models

on:  # yamllint disable-line rule:truthy
    push: null
    pull_request: null

jobs:
  lint-models:
    runs-on: self-hosted
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
            python-version: "3.10"
      - name: Install SQLFluff
        run: "pip install sqlfluff==3.0.3"
      - name: Lint models
        run: "sqlfluff lint Coffee/migrations"