name: SQLFluff Reviewdog

on:
  pull_request:
    #paths:
      #- 'Coffee/migrations/**.sql'

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff
          pip install reviewdog==2.0.7

      - name: Lint SQL files
        run: |
          sqlfluff lint --dialect mysql ${{ github.workspace }}/Coffee/migrations/**.sql \
            | reviewdog -efm="%f:%l:%c: %m" -name=sqlfluff -reporter=github-pr-check