name: Delete Old Workflow Runs

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  del_runs:
    runs-on: self-hosted
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
