name: Get Committer Info

on:
  workflow_dispatch:

jobs:
  get-committer-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Committer GitHub Username
        id: committer_username
        run: |
          COMMITTER_EMAIL=$(git log -1 --pretty=format:%ae)
          GITHUB_USERNAME=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/search/users?q=$COMMITTER_EMAIL" | jq -r '.items[0].login')
          echo "::set-output name=COMMITTER_USERNAME::$GITHUB_USERNAME"

      - name: Print Committer Information
        run: |
          echo "Committer Name: ${{ github.event.head_commit.committer.name }}"
          echo "Committer Email: ${{ github.event.head_commit.committer.email }}"
          echo "Committer GitHub Username: ${{ steps.committer_username.outputs.COMMITTER_USERNAME }}"    
      
      - name: List SQL files
        run: |
          find ${{ github.workspace }} -name "*.sql"