on:
    workflow_dispatch: # Manually trigger the workflow
  
env:
    FLYWAY_LICENSE_KEY: ${{ secrets.FLYWAY_LICENSE_KEY }}
    FIRST_UNDO_SCRIPT: ${{ secrets.FIRST_UNDO_SCRIPT }}
    ACTIONS_RUNNER_DEBUG: true
            
jobs:
    info:
      runs-on: self-hosted
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Variable Informations
          run: |
            echo "${{ toJson(github)}}"

        - name: Who commited?
          run: |
            echo "${{ github.event.commits.commiter.name}}"
            
        - name: List SQL files
          run: |
            find ${{ github.workspace }} -name "*.sql"