name: sqlfluff with reviewdog

on:
  pull_request:

jobs:
  lint-check:
    name: sqlfluff (github-check)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          sqlfluff_version: "2.0.7"
          sqlfluff_command: "lint"
          config: "Coffee/.sqlfluff"
          paths: 'Coffee/migrations'
          level: warning
          dialect: mysql
      - name: Generate Report
        run: |
          echo ":warning: A action finalizou, porem, encontrei correções necessárias nos arquivos abaixo:" >> $GITHUB_STEP_SUMMARY
          jq -r '.[] | .filepath as $filepath | .violations[] | "\($filepath) \(.line_no) \(.line_pos) \(.description)"' sqlfluff-lint.json | awk 'BEGIN {print "<table><tr><td>Arquivo</td><td>Número da Linha</td><td>Posição</td><td>Descrição</td></tr>"} {print "<tr><td>" $1 "</td><td>" $2 "</td><td>" $3 "</td><td>" $4 "</td></tr>"} END {print "</table>"}' >> $GITHUB_STEP_SUMMARY

          #jq -r '.[] | .filepath as $filepath | .violations[] | "<tr><td>\($filepath)</td><td>\(.line_no)</td><td>\(.line_pos)</td><td>\(.description)</td></tr>"' sqlfluff-lint.json |  awk 'BEGIN {print "<table>"} {print} END {print "</table>"}' >> $GITHUB_STEP_SUMMARY
          #jq -r '.[] | .filepath as $filepath | .violations[] | "<tr><td>\($filepath)</td><td>\(.line_no)</td><td>\(.line_pos)</td><td>\(.description)</td></tr>"' sqlfluff-lint.json |  (echo "<table>"; cat -; echo "</table>")
