name: sqlfluff with reviewdog

on:
  pull_request

jobs:

  lint-check:
    name: sqlfluff (github-check)
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          #reporter: github-check
          reporter: github-pr-review
          sqlfluff_version: "3.0.3"
          sqlfluff_command: "lint"
          config: "Coffee/.sqlfluff"
          paths: 'Coffee/migrations'
          level: warning

      - name: Generate GITHUB_STEP_SUMMARY
        env:
          GITHUB_STEP_SUMMARY: ${{ env.GITHUB_STEP_SUMMARY }}
        run: |
          echo "### :warning: SQL Linting Warnings" >> $GITHUB_STEP_SUMMARY
  
          warnings=$(echo '${{ steps.lint-sql.outputs.github-pr-review }}' | jq -r '.annotations[].message')
          if [ -n "$warnings" ]; then
            echo "$warnings" | sed 's/^/  - /g' >> $GITHUB_STEP_SUMMARY
          else
            echo "  No warnings found." >> $GITHUB_STEP_SUMMARY
          fi
