name: Lint
on:
  push:
    branches:
      - main

env:
  FLYWAY_LICENSE_KEY: ${{ secrets.FLYWAY_LICENSE_KEY }}
  FIRST_UNDO_SCRIPT: ${{ secrets.FIRST_UNDO_SCRIPT }}
  ACTIONS_RUNNER_DEBUG: true

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint SQL files
        run: |
          find ${{ github.workspace }}/*/migrations -name 'V*.sql' -exec sqlfluff lint {} --dialect mysql --format=human \; | grep "==" | awk '{ print $2" "$3 }' | sed 's/\[//g' | sed 's/\]//g' > lintReport.txt

  fix:
    needs:
      - lint
    runs-on: self-hosted
    steps:
      - name: Check for FAIL
        id: check-4-fail
        run: |
          if grep -q 'FAIL' lintReport.txt; then
            echo "FAIL found in lintReport.txt. Exiting the workflow."
            echo "HAS_FAIL=true" >> $GITHUB_ENV
          else
            echo "No FAIL found in lintReport.txt. Continuing with the workflow."
            echo "HAS_FAIL=false" >> $GITHUB_ENV
          fi
      - name: Fix SQL Files and generate report
        if: success()
        run: |
          find ${{ github.workspace}}/*/migrations -name '*.sql' -exec sqlfluff fix {} --dialect mysql --force \; >> lintFixReport.txt
      - name: Show me the outputs
        run: echo "${{ toJson(env)}}"

  smile:
    needs:
      - fix
    runs-on: self-hosted
    env:
      YESorNO: ${{ needs.fix.outputs.HAS_FAIL }}
    steps:
      - name: Getting vars from previous job
        run: echo "Did I Get it? $YESorNO"