name: sqlfluff with reviewdog

on:
  pull_request:

jobs:
  lint-check:
    name: sqlfluff (github-check)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          sqlfluff_version: "2.0.7"
          sqlfluff_command: "lint"
          config: "Coffee/.sqlfluff"
          paths: 'Coffee/migrations'
          level: warning
          dialect: mysql
      - name: Generate GITHUB_STEP_SUMMARY
        run: |
          echo "### :warning: SQL Linting Warnings" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo " ======" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.sqlfluff-with-reviewdog-in-composite.outputs.sqlfluff-results }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}" 
        env:
          GITHUB_STEP_SUMMARY: ${{ github.step_summary }}
      - name: Generate Report
        run: |
          echo ":warning: " >> $GITHUB_STEP_SUMMARY
          jq -r '.[] | .filepath as $filepath | .violations[] | "<tr><td>\($filepath)</td><td>\(.line_no)</td><td>\(.line_pos)</td><td>\(.description)</td></tr>"' sqlfluff-lint.json | \ awk 'BEGIN {print "<table>"} {print} END {print "</table>"}' >> $GITHUB_STEP_SUMMARY
