name: Lint
on:
  push:
    branches:
      - main
    #paths: '*/migrations/*.sql'

env:
  FLYWAY_LICENSE_KEY: ${{ secrets.FLYWAY_LICENSE_KEY }}
  FIRST_UNDO_SCRIPT: ${{ secrets.FIRST_UNDO_SCRIPT }}
  ACTIONS_RUNNER_DEBUG: true

jobs:
  lint:
    runs-on: self-hosted
    outputs:
      has_fail: ${{ steps.check4fail.outputs.HAS_FAIL}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint SQL files
        run: |
          find ${{ github.workspace }}/*/migrations -name 'V*.sql' -exec sqlfluff lint {} --dialect mysql --format=human \; | grep "==" | awk '{ print $2" "$3 }' | sed 's/\[//g' | sed 's/\]//g' > lintReport.txt
      - name: Check for FAIL
        id: check4fail
        run: |
          if grep -q 'FAIL' lintReport.txt; then
            echo "FAIL found in lintReport.txt."
            echo "HAS_FAIL=true" >> $GITHUB_OUTPUT
          else
            echo "No FAIL found in lintReport.txt"
            echo "HAS_FAIL=false" >> $GITHUB_OUTPUT
          fi
      - name: Fix SQL Files and generate report
        if: ${{ steps.check4fail.outputs.HAS_FAIL == 'true' }}
        run: |
          find ${{ github.workspace}}/*/migrations -name '*.sql' -exec sqlfluff fix {} --dialect mysql --force \; >> lintFixReport.txt
      - name: Uploading fixed sql files and report
        uses: actions/upload-artifact@v3
        with:
          name: Fixed-Migrations & Lint Fix Report
          path: |
            ${{ github.workspace}}/*/migrations
            lintFixReport.txt