name: Lint
on:
  pull_request:
    # paths: '*/migrations/*.sql'  # Uncomment and adjust if necessary

env:
  FLYWAY_LICENSE_KEY: ${{ secrets.FLYWAY_LICENSE_KEY }}
  FIRST_UNDO_SCRIPT: ${{ secrets.FIRST_UNDO_SCRIPT }}
  ACTIONS_RUNNER_DEBUG: true

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      has_fail: ${{ steps.check4fail.outputs.HAS_FAIL }}
      changed_files: ${{ steps.changed-files.outputs.HAS_CHANGED }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-linter
        uses: super-linter/super-linter@v5.7.2  # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}