name: sqlfluff with reviewdog

on:
  pull_request

jobs:

  lint-check:
    name: sqlfluff (github-check)
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          #reporter: github-check
          sqlfluff_version: "3.0.3"
          sqlfluff_command: "lint"
          config: "Coffee/.sqlfluff"
          paths: 'Coffee/migrations'
          level: warning