name: sqlfluff with reviewdog
on:  # yamllint disable-line rule:truthy
    pull_request
jobs:
  test-check:
    name: runner / sqlfluff (github-check)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "3.0.3"
          #sqlfluff_command: "lint" # Or "lint"
          sqlfluff_command: "python warning_as_error_reporter.py {config} {paths}"
          config: "Coffee/.sqlfluff"
          paths: 'Coffee/migrations'
          fail_on_warnings: true
      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'