name: Lint
on:
  push:
    branches: 
      - dev

env:
  FLYWAY_LICENSE_KEY: ${{ secrets.FLYWAY_LICENSE_KEY }}
  FIRST_UNDO_SCRIPT: ${{ secrets.FIRST_UNDO_SCRIPT }}
  ACTIONS_RUNNER_DEBUG: true

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-linter
        uses: super-linter/super-linter@v5.7.2  # x-release-please-version
        env:
          RUN_LOCAL: true
          DEFAULT_WORKSPACE: "${{ github.workspace }}"
          LINTER_RULES_PATH: "/tmp/linter_rules"
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CODEBASE_PATH: "*/migrations/"

      - name: Run Super Linter for MySQL SQL files
        run: |
          docker exec -e RUN_LOCAL=true -e DEFAULT_WORKSPACE="${{ github.workspace }}" -e LINTER_RULES_PATH=/tmp/linter_rules githubsuperlinter --only changed --linter mysql