name: SQL-LINT

on:
  pull_request:


jobs:
  lint-check:
    name: SQLFluff - LINT
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Check workspace
        run: echo '${{ github.workspace }}'
      - name: Get Token
        id: get_workflow_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.GH_APP_FW_ID }}
          private_key: ${{ secrets.GH_APP_FW_KEY }}
      - name: Checkout this wonderfull project
        uses: actions/checkout@v4
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
      - name: Let's get sqlfluff in action 
        uses: yu-iskw/action-sqlfluff@v3
        with:
          github_token: ${{ steps.get_workflow_token.outputs.token }}
          reporter: github-pr-review
          sqlfluff_version: "3.0.3"
          sqlfluff_command: "lint"
          config: 'Coffee/.sqlfluff'
          paths: 'Coffee/migrations'
          level: warning
          dialect: mysql
      - name: Check if sqlfluff-lint.json exists
        id: check_file
        run: |
          if test -f "sqlfluff-lint.json"; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi

      - name: Generate Report
        if: env.file_exists == 'true'
        run: |
          echo ":warning: A action finalizou, porém, encontrei correções necessárias nos arquivos abaixo:" >> $GITHUB_STEP_SUMMARY
          # Abaixo versão 2.0.7
          #jq -r '.[] | .filepath as $filepath | .violations[] | "\($filepath) \(.line_no) \(.line_pos) \(.description)"' sqlfluff-lint.json | awk 'BEGIN {print "<table><tr><td>Arquivo</td><td>Número da Linha</td><td>Posição</td><td>Descrição</td></tr>"} {printf "<tr><td>%s</td><td>%s</td><td>%s</td><td>", $1, $2, $3; for (i=4; i<=NF; i++) printf "%s ", $i; print "</td></tr>"} END {print "</table>"}' >> $GITHUB_STEP_SUMMARY
          # abaixo versão 3.0.3
          jq -r '.[] | .filepath as $filepath | .violations[] | "\($filepath) \(.start_line_no) \(.start_line_pos) \(.description)"' sqlfluff-lint.json | awk 'BEGIN {print "<table><tr><td>:gift: <b>Arquivo</td><td>:hammer: <b>Número da Linha</td><td>:bomb: <b>Posição</td><td>:page_facing_up: <b>Descrição</td></tr>"} {printf "<tr><td>%s</td><td>%s</td><td>%s</td><td>", $1, $2, $3; for (i=4; i<=NF; i++) printf "%s ", $i; print "</td></tr>"} END {print "</table>"}' >> $GITHUB_STEP_SUMMARY

      - name: Generate Report - When File Does Not Exist
        if: env.file_exists == 'false'
        run: |
          echo ":information_source: Não foram encontrados correções necessárias." >> $GITHUB_STEP_SUMMARY