name: Main

on:
  push:
    branches:
      - main

jobs:
  persist:
    runs-on: self-hosted
    steps:
      - name: Clean Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/Coffee 
          key: ${{ runner.os }}-${{ hashFiles('**/*.sql') }}
          restore-keys: |
            ${{ runner.os }}
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: preseeded-code

      - name: Persist code to workspace
        uses: actions/upload-artifact@v2
        with:
          name: preseeded-code
          path: preseeded-code

  info:
    runs-on: self-hosted
    needs:
      - persist
    steps:      
      - name: Runner Execution Directory
        run: |
          echo ${{ github.workspace }}

      - name: List SQL files
        run: |
          find ${{ github.workspace }} -name "*.sql" 

  sqlfluff-lint:
    runs-on: self-hosted
    needs: info
    steps:
      - name: Check with SqlFluff
        id: lint-sql
        uses: yu-iskw/action-sqlfluff@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "2.0.7"
          sqlfluff_command: "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: ${{ github.workspace }}/**/*.sql
          github_base_ref: "main"

      - name: Upload SQLFluff Lint Error Report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: sqlfluff-lint-error-report
          path: fixed_sqlfluff_lint_error_report.xml

  sqlfluff-fix:
    runs-on: self-hosted
    needs: sqlfluff-lint
    steps:
      - name: Fix with SqlFluff
        uses: yu-iskw/action-sqlfluff@v3
        with:
          github_token: ${{ secrets.github_token }}
          sqlfluff_version: "2.0.7"
          sqlfluff_command: "fix"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: ${{ github.workspace }}/Coffee/migrations/*.sql
          github_base_ref: "main"

      - name: Upload SQLFluff Fix Error Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: sqlfluff-fix-error-report
          path: fixed_sqlfluff_fix_error_report.xml

  migrate:
    runs-on: self-hosted
    needs:
      - sqlfluff-fix

    steps:
      - name: Migrate Step
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:mysql://192.168.0.116:3306/${{ secrets.DB }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.DB_PASSWORD }}
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true

      - name: Upload Flyway Report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: flyway-report
          path: flyway_report.xml
