name: Flyway Migration

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flyway
        run: |
          docker pull flyway/flyway:7.14.0
          export FLYWAY_URL=jdbc:mysql://192.168.0.161:3306/${{ secrets.DB }}
          export FLYWAY_USER=${{ secrets.USER }}
          export FLYWAY_PASSWORD=${{ secrets.DB_PASSWORD }}
          export FLYWAY_LOCATIONS=filesystem:${{ github.workspace }}/Coffee/migrations

      - name: Run Flyway Migrations
        run: |
          docker run --rm -v "${{ github.workspace }}/Coffee/migrations:/flyway/sql" \
            -e FLYWAY_URL -e FLYWAY_USER -e FLYWAY_PASSWORD -e FLYWAY_LOCATIONS \
            flyway/flyway:7.14.0 migrate