name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  info:
    runs-on: self-hosted
    outputs:
      step1_result: ${{ steps.step1_result.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Runner Execution Directory
        id: step1
        run: |
          echo "::set-output name=result::${{ github.workspace }}"

      - name: List SQL files
        run: |
          find ${{ github.workspace }} -name "*.sql"

  lint:
    needs:
      - info
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set GitHub token for reviewdog
        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Get info result
        id: step1
        run: |
          echo "Result from info: ${{ needs.info.outputs.step1_result }}"

      - name: Lint SQL files and generate reviewdog report
        run: |
          sqlfluff lint ${{ needs.info.outputs.step1_result }}/Coffee/migrations --dialect mysql --format=human | /home/thierry/go/bin/reviewdog -f=sqlfluff -reporter=github-pr-review -tee -level=info