name: Main

on:
  push:
    branches:
      - main

jobs:
  sqlfluff-reviewdog:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check with SqlFluff and Reviewdog
        id: lint-sql
        run: |
         /home/thierry/.local/bin/sqlfluff lint --format=human ${{ github.workspace }}/Coffee/migrations/*.sql | /home/thierry/action-setup/bin/reviewdog -reporter=github-pr-review -level=info

      - name: Save SQLFluff Report
        if: failure()
        run: echo "${{ steps.lint-sql.outputs.sqlfluff-results }}" > sqlfluff_OutPut_report.html

  migrate:
    runs-on: self-hosted
    needs:
      - sqlfluff-reviewdog

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Migrate Step
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:mysql://192.168.0.116:3306/${{ secrets.DB }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.DB_PASSWORD }}
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true

      - name: Upload SQLFluff Report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: sqlfluff-report
          path: sqlfluff_OutPut_report.html
