name: Main

on:
  push:
    branches:
      - main

jobs:
  info:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Runner Execution Directory
        run: |
          echo ${{ github.workspace }}

      - name: List SQL files
        run: |
          find ${{ github.workspace }} -name "*.sql"

  lint:
    needs:
      - info
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint SQL files and generate reviewdog report
        run: |
          sqlfluff lint ${{ github.workspace }}/Coffee/migrations --dialect mysql --format=reviewdog | /home/thierry/go/bin/reviewdog -f=sqlfluff -reporter=github-pr-review