name: Main
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:mysql://192.168.60.65:3306/coffeeshop
          user: coffeemng
          password: r0y4lcoffee
      - run: echo 'testing'
