name: Main

on:
  push:
    branches:
      - main

jobs:
  sqlfluff:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check with SqlFluff
        id: lint-sql
        uses: yu-iskw/action-sqlfluff@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "2.0.7"
          sqlfluff_command: "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: ${{ github.workspace }}/Coffee/migrations/*.sql
          github_base_ref: "main"

      - name: Save SQLFluff Report
        if: failure()
        run: echo "${{ steps.lint-sql.outputs.sqlfluff-results }}" > sqlfluff_OutPut_report.xml

  fix:
    runs-on: self-hosted
    needs: sqlfluff
    if: failure()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fix with SqlFluff
        uses: yu-iskw/action-sqlfluff@v3
        with:
          github_token: ${{ secrets.github_token }}
          sqlfluff_version: "2.0.7"
          sqlfluff_command: "fix"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: ${{ github.workspace }}/Coffee/migrations/*.sql
          github_base_ref: "main"

      - name: Save Fixed SQLFluff Report
        run: echo "${{ steps.lint-sql.outputs.sqlfluff-results }}" > fixed_sqlfluff_OutPut_report.xml

  migrate:
    runs-on: self-hosted
    needs:
      - fix

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Migrate Step
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:mysql://192.168.0.116:3306/${{ secrets.DB }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.DB_PASSWORD }}
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true

      - name: Upload SQLFluff Report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: sqlfluff-report
          path: fixed_sqlfluff_OutPut_report.xml
