name: Main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Code Step
        uses: Bidaya0/sql-lint-in-action@v0.0.2
        with:
          path: ${{ github.workspace }}/Coffee/migrations
          host: 192.168.60.65
          user: coffeemng
          password: r0y4lcoffee
          driver: mysql
          port: 3306
          ignore_errors:

  migrate:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Migrate Step
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:mysql://192.168.60.65:3306/coffeeshop
          user: coffeemng
          password: r0y4lcoffee

      - name: Run additional tests
        run: echo 'testing'
