name: Flyway Migration

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flyway
        run: |
          docker pull flyway/flyway:7.14.0
          export FLYWAY_URL="jdbc:mysql://192.168.0.191:3306/${{ secrets.DB }}"
          export FLYWAY_USER="coffeemng"
          export FLYWAY_PASSWORD="r0y4lcoffee"
          export FLYWAY_LOCATIONS=filesystem:"${{ github.workspace }}/Coffee/migrations"

      - name: Run Flyway Migrations
        run: |
          docker run --rm -v "${{ github.workspace }}/Coffee/migrations:/flyway/sql" \
            -e FLYWAY_URL -e FLYWAY_USER -e FLYWAY_PASSWORD -e FLYWAY_LOCATIONS \
            flyway/flyway:7.14.0 migrate