name: Main

on: 
  workflow_dispatch:

env:
  FLYWAY_LICENSE_KEY: ${{ secrets.FLYWAY_LICENSE_KEY }}
  FIRST_UNDO_SCRIPT: ${{ secrets.FIRST_UNDO_SCRIPT }}
  ACTIONS_RUNNER_DEBUG: true

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint SQL files and generate report
        run: |
          #find ${{ github.workspace }}/*/migrations -name '*.sql' -exec sqlfluff lint {} --dialect mysql --format=human \; >> lintReport.txt
          find  ${{ github.workspace }}/*/migrations -name 'V*.sql' -exec sqlfluff lint {} --dialect mysql --format=human \; | grep "==" | awk '{ print $2" "$3 }' | sed 's/\[//g' | sed 's/\]//g' > lintReport.txt
          echo "next line"


  fix:
    needs:
      - lint
    runs-on: self-hosted
    steps:
      - name: Fix SQL Files and generate report
        run: |
           find ${{ github.workspace}}/*/migrations -name '*.sql' -exec sqlfluff fix {} --dialect mysql  --format=human --force \; >> lintFixReport.txt

  build:
    needs:
      - fix
    name: Deploy Build - Development Database
    runs-on: self-hosted
    environment: 'build'
    env:
      stage: 'Build'
      databaseName: ${{ secrets.databaseName }}
      JDBC: ${{ secrets.JDBC }}
      userName: ${{ secrets.userName }}
      password: ${{ secrets.password }}
      displayName: 'Build'
      executeBuild: true
      publishArtifacts: true

    steps:
#      - uses: actions/checkout@v3

      - name: Create Flyway Command Variable
        if: ${{ true }}
        run: |
          echo "FLYWAY_COMMAND='sudo /usr/local/bin/flyway -user=${{ env.userName }} -password=${{ env.password }}  -configFiles=${{ GITHUB.WORKSPACE }}/Coffee/flyway.toml -locations=filesystem:${{ GITHUB.WORKSPACE }}/Coffee/migrations -baselineOnMigrate=true'" >> $GITHUB_ENV
        continue-on-error: true

      - name: Clean Build DB
        if: env.executeBuild == 'true'
        run: |
          eval ${{ env.FLYWAY_COMMAND }} info clean info -url="${{ env.JDBC }}" -cleanDisabled='false'

      - name: Migrate Build DB
        if: env.executeBuild == 'true'
        run: |
          eval ${{ env.FLYWAY_COMMAND }} info migrate info -url="${{ env.JDBC }}" -cleanDisabled='false'

      - name: Stage files for publishing
        if: env.publishArtifacts == 'true'
        run: |
          mkdir -p Artifact_Files/Migration/
          cp -R ${{ GITHUB.WORKSPACE }}/Coffee/migrations Artifact_Files/Migration/

      - name: Publish Validated Migration Scripts as Artifact #if:: env.publishArtifacts == 'true'
        uses: actions/upload-artifact@v3.1.1
        with:
          name: flyway-build-artifact
          path: Artifact_Files/Migration/

# Build is ok, going to change report production

  prod-preparation:
    name: Production Deployment Preparation - Report Creation
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: 'prod' #Ensure this environment name is setup in the projects Settings>Environment area. Ensuring any reviewers are also configured
    if: ${{ true }} #Set this variable to false to temporarily disable the job
    needs: build
    env:
      stage: 'Prod'
      # Environment Secrets - Ensure all of the below have been created as an Environment Secret (Projects Settings > Secrects > Actions section, specially related to the environment in question) #
      databaseName: ${{ secrets.databaseName}}
      JDBC: ${{ secrets.JDBC }}
      userName: ${{ secrets.userName }}
      password: ${{ secrets.password }}
      # End of Environment Secrets #
      generateDriftAndChangeReport: true
      failReleaseIfDriftDetected: false
      staticCodeAnalysis: true #Currently not setup in this pipeline
      publishArtifacts: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create Flyway Command Variable
        if: ${{ true }}
        run: |
          echo "FLYWAY_COMMAND='sudo /usr/local/bin/flyway -user=${{ env.userName }} -password=${{ env.password }}  -configFiles=${{ GITHUB.WORKSPACE }}/Coffee/flyway.toml -locations=filesystem:${{ GITHUB.WORKSPACE }}/Coffee/migrations -baselineOnMigrate=true'" >> $GITHUB_ENV
        continue-on-error: true
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3
        
      # Runs the Flyway Check command, to produce a deployment report, against the Production database
      - name: Create Check Reports
#        if: env.generateDriftAndChangeReport == 'true'
        run: |
          mkdir -p ${{ GITHUB.WORKSPACE }}/Coffee/reports
          eval ${{ env.FLYWAY_COMMAND }} -user="${{ env.userName }}" -password="${{ env.password }}" -baselineOnMigrate="true"  -configFiles="${{ GITHUB.WORKSPACE }}/Coffee/flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}/*/migrations" check -dryrun -changes -drift "-check.failOnDrift=${{ env.failReleaseIfDriftDetected }}" "-check.buildUrl=${{ env.JDBC }}" "-check.buildUser=${{ env.username }}" "-check.buildPassword=${{ env.password }}" -url="${{ env.JDBC }}" "-check.reportFilename=${{ GITHUB.WORKSPACE }}/Coffee/reports/${{ env.databaseName }}-Run-${{ GITHUB.RUN_ID }}-Check-Report.html"
        continue-on-error: true

      # Create a directory to stage the artifact files
      - name: Stage files for publishing
        if: env.publishArtifacts == 'true'
        run: |
          mkdir -p Artifact_Files/Reports/ ${{ GITHUB.WORKSPACE }}/Coffee/reports
          cp -R ${{ GITHUB.WORKSPACE }}/Coffee/reports Artifact_Files/Reports/

      - name: Publish Check Report as Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: flyway-reports
          path: Artifact_Files/Reports/


# step where if migration on in dev, will continue to here

  prod:
    name: Deploy Production - Migration
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: 'prod' #Ensure this environment name is setup in the projects Settings>Environment area. Ensuring any reviewers are also configured 
    if: ${{ true }} #Set this variable to false to temporarily disable the job
    needs: prod-preparation
    env:
      stage: 'Prod'
      databaseName: ${{ secrets.databaseName}}
      JDBC: ${{ secrets.JDBC }}
      userName: ${{ secrets.userName }}
      password: ${{ secrets.password }}
      pauseForCodeReview: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3

      - name: Create Flyway Command Variable
        if: ${{ true }}
        run: |
          echo "FLYWAY_COMMAND='sudo /usr/local/bin/flyway -user=${{ env.userName }} -password=${{ env.password }}  -configFiles=${{ GITHUB.WORKSPACE }}/Coffee/flyway.toml -locations=filesystem:${{ GITHUB.WORKSPACE }}/Coffee/migrations -baselineOnMigrate=true'" >> $GITHUB_ENV
        continue-on-error: true
        
      # Runs the Flyway Migrate against the Production database
      - name: Migrate Build DB
        if: ${{ true }}
        run: |
          eval ${{ env.FLYWAY_COMMAND }} -user="${{ env.userName }}" -password="${{ env.password }}" -baselineOnMigrate="true" -configFiles="${{ GITHUB.WORKSPACE }}/flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}/*/migrations" info migrate info -url="${{ env.JDBC }}" -cleanDisabled='false'