name: Main

on:
  push:
    branches:
      - main

jobs:
  info:
    runs-on: self-hosted
    steps:
     
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Runner Execution Directory
        run: |
          echo ${{ github.workspace }}

      - name: List SQL files
        run: |
          find ${{ github.workspace }} -name "*.sql" 
        
  sqlfluff-lint:
    needs: 
      - info 
    runs-on: self-hosted    
    steps: 
      - name: Lint SQL files
        run: |
          sqlfluff lint ${{ github.workspace }}/Coffee/migrations