name: Main

on:
  push:
    branches:
      - main

jobs:
  info:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Runner Execution Directory
        run: |
          echo ${{ github.workspace }}

      - name: List SQL files
        run: |
          find ${{ github.workspace }} -name "*.sql"

  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Install reviewdog
        run: |
          # Replace the URL with the latest release of reviewdog
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v0.12.0

          - name: Set GitHub token for reviewdog
          run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
  
      - name: Lint SQL files and generate reviewdog report
        run: |
          sqlfluff lint ${{ github.workspace }}/Coffee/migrations --dialect mysql --format=reviewdog | $(go env GOPATH)/bin/reviewdog -f=sqlfluff -reporter=github-pr-review