name: Main
on:
  - push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: Bidaya0/sql-lint-in-action@v0.0.2
        with:
          path: ../Coffee/migrations
          host: 192.168.60.65
          user: coffeemng
          password: r0y4lcoffee
          driver: mysql
          port: 3306
          ignore_errors:
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:mysql://192.168.60.65:3306/coffeeshop
          user: coffeemng
          password: r0y4lcoffee
      - run: echo 'testing'
