name: build
on:
  push
#  workflow_run:
#    workflows: ["Lint"]
#    types:
#      - completed

env:
  FLYWAY_LICENSE_KEY: ${{ secrets.FLYWAY_LICENSE_KEY }}
  FIRST_UNDO_SCRIPT: ${{ secrets.FIRST_UNDO_SCRIPT }}
  ACTIONS_RUNNER_DEBUG: true

jobs:
  lint:
    runs-on: self-hosted
    outputs:
      has_fail: ${{ steps.check4fail.outputs.HAS_FAIL}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint SQL files
        run: |
          find ${{ github.workspace }}/*/migrations -name 'V*.sql' -exec sqlfluff lint {} --dialect mysql --format=human \; | grep "==" | awk '{ print $2" "$3 }' | sed 's/\[//g' | sed 's/\]//g' > lintReport.txt
      - name: Check for FAIL
        id: check4fail
        run: |
          if grep -q 'FAIL' lintReport.txt; then
            echo "FAIL found in lintReport.txt."
            echo "HAS_FAIL=true" >> $GITHUB_OUTPUT
          else
            echo "No FAIL found in lintReport.txt"
            echo "HAS_FAIL=false" >> $GITHUB_OUTPUT
          fi
      - name: Fix SQL Files and generate report
        if: ${{ steps.check4fail.outputs.HAS_FAIL == 'true' }}
        run: |
          find ${{ github.workspace}}/*/migrations -name '*.sql' -exec sqlfluff fix {} --dialect mysql --force \; >> lintFixReport.txt
      - name: Uploading fixed sql files and report
        uses: actions/upload-artifact@v3
        with:
          name: Fixed-Migrations & Lint Fix Report
          path: |
            ${{ github.workspace}}/*/migrations
            lintFixReport.txt
  build:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: lint
    name: Deploy Build - Development Database
    runs-on: self-hosted
    environment: 'build'
    env:
      stage: 'Build'
      databaseName: ${{ secrets.databaseName }}
      JDBC: ${{ secrets.JDBC }}
      userName: ${{ secrets.userName }}
      password: ${{ secrets.password }}
      displayName: 'Build'
      executeBuild: true
      publishArtifacts: true

    steps:
#      - uses: actions/checkout@v3

      - name: Create Flyway Command Variable
        if: ${{ true }}
        run: |
          echo "FLYWAY_COMMAND='sudo /usr/local/bin/flyway -user=${{ env.userName }} -password=${{ env.password }}  -configFiles=${{ GITHUB.WORKSPACE }}/Coffee/flyway.toml -locations=filesystem:${{ GITHUB.WORKSPACE }}/Coffee/migrations -baselineOnMigrate=true'" >> $GITHUB_ENV
        continue-on-error: true

      - name: Clean Build DB
        if: env.executeBuild == 'true'
        run: |
          eval ${{ env.FLYWAY_COMMAND }} info clean info -url="${{ env.JDBC }}" -cleanDisabled='false'

      - name: Migrate Build DB
        if: env.executeBuild == 'true'
        run: |
          eval ${{ env.FLYWAY_COMMAND }} info migrate info -url="${{ env.JDBC }}" -cleanDisabled='false'

      - name: Stage files for publishing
        if: env.publishArtifacts == 'true'
        run: |
          mkdir -p Artifact_Files/Migration/
          cp -R ${{ GITHUB.WORKSPACE }}/Coffee/migrations Artifact_Files/Migration/

      - name: Publish Validated Migration Scripts as Artifact #if:: env.publishArtifacts == 'true'
        uses: actions/upload-artifact@v3.1.1
        with:
          name: flyway-build-artifact
          path: Artifact_Files/Migration/

# Build is ok, going to change report production

  prod-preparation:
    name: Production Deployment Preparation - Report Creation
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: 'prod' #Ensure this environment name is setup in the projects Settings>Environment area. Ensuring any reviewers are also configured
    if: ${{ true }} #Set this variable to false to temporarily disable the job
    needs: build
    env:
      stage: 'Prod'
      # Environment Secrets - Ensure all of the below have been created as an Environment Secret (Projects Settings > Secrects > Actions section, specially related to the environment in question) #
      databaseName: ${{ secrets.databaseName}}
      JDBC: ${{ secrets.JDBC }}
      userName: ${{ secrets.userName }}
      password: ${{ secrets.password }}
      # End of Environment Secrets #
      generateDriftAndChangeReport: true
      failReleaseIfDriftDetected: false
      staticCodeAnalysis: true #Currently not setup in this pipeline
      publishArtifacts: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create Flyway Command Variable
        if: ${{ true }}
        run: |
          echo "FLYWAY_COMMAND='sudo /usr/local/bin/flyway -user=${{ env.userName }} -password=${{ env.password }}  -configFiles=${{ GITHUB.WORKSPACE }}/Coffee/flyway.toml -locations=filesystem:${{ GITHUB.WORKSPACE }}/Coffee/migrations -baselineOnMigrate=true'" >> $GITHUB_ENV
        continue-on-error: true
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3
        
      # Runs the Flyway Check command, to produce a deployment report, against the Production database --- # "-check.reportFilename=${{ GITHUB.WORKSPACE }}/Coffee/reports/${{ env.databaseName }}-Run-${{ GITHUB.RUN_ID }}-Check-Report.html"
      - name: Create Check Reports
        if: env.generateDriftAndChangeReport == 'true'
        run: |
          export FLYWAY_LICENSE_KEY=FL0130EF05E5BA26F601A4F82DF5A0AFCD8D834E89E0734AF37C290B4F90157F3654A917A6B692B6F0C5D6830771B1BDBC642487701E3B5022E7C4EC66DAF677722607B61768EC8912171F32AA9D76907C0A4AA5D1C851B3E3883EF9B093F1956C821A6C3DD21210D604A5FAD071FDC4D4C195D41D7A89FAD9833A1055A347D6484618021A1F6D702AADEAC75F0692AEC49E92E70CE079F4475BD7596F6D4A24F185223A1F7FAFF859379BA623543CCE6AA67E1A3613408D0B5406BD83ED5509B3CEFF807178886F3191C79C49FDB820B66805909F0A9AFA852D27C09C8E9017B2D3B91C8000775D0EC3B929A42472DD5BFC516F585521C48DA32484FE3EE2BB1C69
          eval sudo /usr/local/bin/flyway -user="${{ env.userName }}" -password="${{ env.password }}" -baselineOnMigrate="true"  -configFiles="${{ GITHUB.WORKSPACE }}/Coffee/flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}/*/migrations" check -dryrun -drift "-check.failOnDrift=${{ env.failReleaseIfDriftDetected }}" "-check.buildUrl=${{ env.JDBC }}" "-check.buildUser=${{ env.username }}" "-check.buildPassword=${{ env.password }}" -url="${{ env.JDBC }}"
        continue-on-error: true
#eval sudo /usr/local/bin/flyway -user="${{ env.userName }}" -password="${{ env.password }}" -baselineOnMigrate="true"  -configFiles="${{ GITHUB.WORKSPACE }}/Coffee/flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}/*/migrations" check -dryrun -changes -drift "-check.failOnDrift=${{ env.failReleaseIfDriftDetected }}" "-check.buildUrl=${{ env.JDBC }}" "-check.buildUser=${{ env.username }}" "-check.buildPassword=${{ env.password }}" -url="${{ env.JDBC }}"
      - name: Publish Check Report as Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: flyway-reports
          path: report.html


# step where if migration on in dev, will continue to here

  prod:
    name: Deploy Production - Migration
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: 'prod' #Ensure this environment name is setup in the projects Settings>Environment area. Ensuring any reviewers are also configured 
    if: ${{ true }} #Set this variable to false to temporarily disable the job
    needs: prod-preparation
    env:
      stage: 'Prod'
      databaseName: ${{ secrets.databaseName}}
      JDBC: ${{ secrets.JDBC }}
      userName: ${{ secrets.userName }}
      password: ${{ secrets.password }}
      pauseForCodeReview: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3

      - name: Create Flyway Command Variable
        if: ${{ true }}
        run: |
          echo "FLYWAY_COMMAND='sudo /usr/local/bin/flyway -user=${{ env.userName }} -password=${{ env.password }}  -configFiles=${{ GITHUB.WORKSPACE }}/Coffee/flyway.toml -locations=filesystem:${{ GITHUB.WORKSPACE }}/Coffee/migrations -baselineOnMigrate=true'" >> $GITHUB_ENV
        continue-on-error: true
        
      # Runs the Flyway Migrate against the Production database
      - name: Migrate Build DB
        if: ${{ true }}
        run: |
          eval sudo /usr/local/bin/flyway -user="${{ env.userName }}" -password="${{ env.password }}" -baselineOnMigrate="true" -configFiles="${{ GITHUB.WORKSPACE }}/flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}/*/migrations" info migrate info -url="${{ env.JDBC }}" -cleanDisabled='false'