name: reviewdog

on:
  push:
    branches:
      - main
  pull_request:
jobs:
    actionlint:
        name: runner / actionlint
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: reviewdog/action-actionlint@v1
            with:
              reporter: github-check
              level: warning