name: reviewdog
on:
    workflow_dispatch:
jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          level: warning


  actionlint:
    name: runner / actionlint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          level: warning